### PR TITLE
Add reminder

### PR DESCRIPTION
**Pull request by hydride0**
A simple reminder that permits you to remind something in the future. At the moment you can only remind in the same day you launch it specifying hour and minutes as in the simple following command:
    !rem 21:34 Eat a hamburger

It may be improved in the future with support for particular days or so.

### CODE REVIEW

**Comment by RoxasShadow** [comment]
:+1:

**Comment by RoxasShadow** [comment]
@hydride0 what about a command to say something when someone currently offline joins a chan?

**Comment by hydride0** [comment]
si`

**Comment by RoxasShadow** [comment]
Ok

**Pull request merged**
